_extends: brince-mono-repo:.github/release-drafter.yml
name-template: 'packages-util-v$RESOLVED_VERSION'
tag-template: 'packages-util-v$RESOLVED_VERSION'
tag-prefix: packages-util-v
include-paths:
  - "packages/util"
