_extends: brince-mono-repo:.github/release-drafter.yml
name-template: 'apps-blog-v$RESOLVED_VERSION'
tag-template: 'apps-blog-v$RESOLVED_VERSION'
tag-prefix: apps-blog-v
include-paths:
  - "apps/blog"
